# Cosine Similarity 餘弦相似度

## cos data匯入

In [25]:
import pandas as pd
import numpy as np
cos1 = pd.read_csv('/Users/hsieh/Downloads/cos_a1.csv')
print(cos1.head())
cos1.shape
cos1_len = len(cos1.columns)

       word       x1       x2       x3       x4       x5       x6       x7  \
0  airplane  0.76030 -0.29243  0.21963 -0.54849  0.08876  0.96001  0.13355
1     beach  0.92768  0.93720 -0.70419  0.66324  0.36995 -0.03304 -0.85956
2   company  0.59972 -0.86568  0.98532  0.28760  0.29583  0.24378  0.58205
3     money -0.42560 -0.35914 -0.92060 -0.16842  0.38835 -0.16788  0.21537
4      wine -0.90236  0.67156 -0.78158  0.65920 -0.92451 -0.90356 -0.72575

        x8       x9  ...      x41      x42      x43      x44      x45  \
0  0.33537 -0.41289  ... -0.11721 -0.86708  0.50353 -0.44880 -0.01190
1 -0.03122 -0.74422  ...  0.79950 -0.27140 -0.13457 -0.00119 -0.12581
2 -0.68428 -0.21353  ... -0.04081  0.68693 -0.05853 -0.93420 -0.67201
3  0.35251 -0.28432  ... -0.18583 -0.58304 -0.58131 -0.55434  0.41802
4 -0.86411 -0.33202  ... -0.32182  0.92887 -0.31721 -0.20863 -0.05857

       x46      x47      x48      x49      x50
0 -0.52148 -0.12889 -0.20130  0.07239  0.63944
1 -0.27554  0.23386 -0.20019  0.73698  0.27505
2 -0.67856 -0.92649 -0.16101 -0.07404  0.30765
3 -0.29154  0.74722  0.51134 -0.37012 -0.00587
4  0.43929  0.61840 -0.15220 -0.46267  0.12214

[5 rows x 51 columns]

In [26]:
# 了解目前系統編碼原則
import sys
print(sys.getdefaultencoding()) 

# 轉碼
## method1：另存新檔

# 開啟Big5 輸入檔案
inFile = open('/Users/hsieh/Downloads/cos_a2.csv', 'r', encoding = 'Big5')

# 開啟UTF-8輸出檔案
outFile = open('/Users/hsieh/Downloads/cos_a2_utf8.csv', 'w', encoding='UTF-8')

# 以Big5編碼讀取檔案
content = inFile.read()
# 以UTF-8編碼寫入檔案
outFile.write(content)

# 關閉檔案
inFile.close()
outFile.close()

utf-8

In [77]:
cos2 = pd.read_csv('/Users/hsieh/Downloads/cos_a2_utf8.csv')
#cos2 = cos2.rename({'x': 'y'}, axis='columns')
print(cos2.head())
cos2_len = len(cos2.columns)

  word       x1       x2       x3       x4       x5       x6       x7  \
0   電信  0.08512  0.71236  0.97080 -0.65088 -0.35349 -0.01062  0.13594
1   娛樂 -0.03229  0.32027  0.02628  0.83389  0.44232  0.32387  0.12808
2   飲食 -0.30166 -0.80396 -0.03770 -0.07119  0.51214 -0.88410  0.91825
3   工作 -0.21242  0.60048  0.40395 -0.45317 -0.72590 -0.95586 -0.55033
4   其他 -0.81556  0.77646 -0.23344 -0.05515  0.15636 -0.98196  0.91148

        x8       x9  ...      x41      x42      x43      x44      x45  \
0  0.56301  0.76103  ...  0.91896 -0.05076  0.13018 -0.77484  0.27393
1 -0.56437  0.85170  ... -0.14576 -0.88940 -0.00593 -0.67063 -0.05713
2  0.74748  0.23407  ... -0.65568 -0.01455 -0.31517  0.41715 -0.26791
3 -0.50572 -0.37572  ... -0.20149 -0.29745 -0.22910  0.45051 -0.20223
4  0.68085 -0.27819  ... -0.45726 -0.17924  0.93577 -0.98173  0.91490

       x46      x47      x48      x49      x50
0 -0.30547  0.21840 -0.79273  0.72521  0.55864
1 -0.47931  0.62492  0.17250  0.66306  0.80183
2 -0.16543 -0.07553 -0.02354  0.11964  0.23436
3  0.26673  0.13882  0.48059  0.90964 -0.59566
4  0.83299 -0.56204  0.82362 -0.37546  0.89169

[5 rows x 51 columns]

In [7]:
cos12.shape

(50, 102)

In [28]:
cos1['key'] = 1
cos2['key'] = 1

cos12 = pd.merge(cos1, cos2, on='key').drop('key', 1)
cos12.head()

,word_x,x1_x,x2_x,x3_x,x4_x,x5_x,x6_x,x7_x,x8_x,x9_x,...,x41_y,x42_y,x43_y,x44_y,x45_y,x46_y,x47_y,x48_y,x49_y,x50_y
0,airplane,0.7603,-0.29243,0.21963,-0.54849,0.08876,0.96001,0.13355,0.33537,-0.41289,...,0.91896,-0.05076,0.13018,-0.77484,0.27393,-0.30547,0.21840,-0.79273,0.72521,0.55864
1,airplane,0.7603,-0.29243,0.21963,-0.54849,0.08876,0.96001,0.13355,0.33537,-0.41289,...,-0.14576,-0.88940,-0.00593,-0.67063,-0.05713,-0.47931,0.62492,0.17250,0.66306,0.80183
2,airplane,0.7603,-0.29243,0.21963,-0.54849,0.08876,0.96001,0.13355,0.33537,-0.41289,...,-0.65568,-0.01455,-0.31517,0.41715,-0.26791,-0.16543,-0.07553,-0.02354,0.11964,0.23436
3,airplane,0.7603,-0.29243,0.21963,-0.54849,0.08876,0.96001,0.13355,0.33537,-0.41289,...,-0.20149,-0.29745,-0.22910,0.45051,-0.20223,0.26673,0.13882,0.48059,0.90964,-0.59566
4,airplane,0.7603,-0.29243,0.21963,-0.54849,0.08876,0.96001,0.13355,0.33537,-0.41289,...,-0.45726,-0.17924,0.93577,-0.98173,0.91490,0.83299,-0.56204,0.82362,-0.37546,0.89169

In [29]:
cos12['word_xy'] = cos12['word_x'] + cos12['word_y']
print(cos12['word_xy'].head())
cos12 = cos12.drop(columns = ['word_x', 'word_y'])
cos12.shape

0    airplane電信
1    airplane娛樂
2    airplane飲食
3    airplane工作
4    airplane其他
Name: word_xy, dtype: object

(50, 101)

In [90]:

# 計算 xiyi = (xi-yi) ** 2
cos_si = pd.DataFrame()

for i in range(1, cos1_len):
    cos_si['x' + str(i) + 'y' + str(i)] = (cos12['x' + str(i) + '_x'] * cos12['x' + str(i) + '_y'])
#    cos_si['x' + str(i) + 'y' + str(i) + '_sum'] = cos_si.iloc[:,101:151].sum(axis=1)

print(cos_si.head())
cos_si['x' + 'y'] = cos_si.sum(axis=1)

       x1y1      x2y2      x3y3      x4y4      x5y5      x6y6      x7y7  \
0  0.064717 -0.208315  0.213217  0.357001 -0.031376 -0.010195  0.018155
1 -0.024550 -0.093657  0.005772 -0.457380  0.039260  0.310918  0.017105
2 -0.229352  0.235102 -0.008280  0.039047  0.045458 -0.848745  0.122632
3 -0.161503 -0.175598  0.088720  0.248559 -0.064431 -0.917635 -0.073497
4 -0.620070 -0.227060 -0.051270  0.030249  0.013879 -0.942691  0.121728

       x8y8      x9y9    x10y10  ...    x41y41    x42y42    x43y43    x44y44  \
0  0.188817 -0.314222  0.195570  ... -0.107711  0.044013  0.065550  0.347748
1 -0.189273 -0.351658  0.099997  ...  0.017085  0.771181 -0.002986  0.300979
2  0.250682 -0.096645  0.155695  ...  0.076852  0.012616 -0.158698 -0.187217
3 -0.169603  0.155131  0.173456  ...  0.023617  0.257913 -0.115359 -0.202189
4  0.228337  0.114862  0.029980  ...  0.053595  0.155415  0.471188  0.440600

     x45y45    x46y46    x47y47    x48y48    x49y49    x50y50
0 -0.003260  0.159296 -0.028150  0.159577  0.052498  0.357217
1  0.000680  0.249951 -0.080546 -0.034724  0.047999  0.512722
2  0.003188  0.086268  0.009735  0.004739  0.008661  0.149859
3  0.002407 -0.139094 -0.017893 -0.096743  0.065849 -0.380889
4 -0.010887 -0.434388  0.072441 -0.165795 -0.027180  0.570182

[5 rows x 50 columns]

In [91]:
print(cos_si.head())

       x1y1      x2y2      x3y3      x4y4      x5y5      x6y6      x7y7  \
0  0.064717 -0.208315  0.213217  0.357001 -0.031376 -0.010195  0.018155
1 -0.024550 -0.093657  0.005772 -0.457380  0.039260  0.310918  0.017105
2 -0.229352  0.235102 -0.008280  0.039047  0.045458 -0.848745  0.122632
3 -0.161503 -0.175598  0.088720  0.248559 -0.064431 -0.917635 -0.073497
4 -0.620070 -0.227060 -0.051270  0.030249  0.013879 -0.942691  0.121728

       x8y8      x9y9    x10y10  ...    x42y42    x43y43    x44y44    x45y45  \
0  0.188817 -0.314222  0.195570  ...  0.044013  0.065550  0.347748 -0.003260
1 -0.189273 -0.351658  0.099997  ...  0.771181 -0.002986  0.300979  0.000680
2  0.250682 -0.096645  0.155695  ...  0.012616 -0.158698 -0.187217  0.003188
3 -0.169603  0.155131  0.173456  ...  0.257913 -0.115359 -0.202189  0.002407
4  0.228337  0.114862  0.029980  ...  0.155415  0.471188  0.440600 -0.010887

     x46y46    x47y47    x48y48    x49y49    x50y50        xy
0  0.159296 -0.028150  0.159577  0.052498  0.357217 -2.369505
1  0.249951 -0.080546 -0.034724  0.047999  0.512722  2.001440
2  0.086268  0.009735  0.004739  0.008661  0.149859 -1.204522
3 -0.139094 -0.017893 -0.096743  0.065849 -0.380889  1.289263
4 -0.434388  0.072441 -0.165795 -0.027180  0.570182 -4.553820

[5 rows x 51 columns]

In [53]:

d = pd.DataFrame()
for i in range(1, cos1_len):
    d['xx' + str(i)] = 0
    d['xx' + str(i)] = cos1['x' + str(i)] ** 2

d['xx'] = d.sum(axis=1) ** .5
print(d.head())

        xx1       xx2       xx3       xx4       xx5       xx6       xx7  \
0  0.578056  0.085515  0.048237  0.300841  0.007878  0.921619  0.017836
1  0.860590  0.878344  0.495884  0.439887  0.136863  0.001092  0.738843
2  0.359664  0.749402  0.970856  0.082714  0.087515  0.059429  0.338782
3  0.181135  0.128982  0.847504  0.028365  0.150816  0.028184  0.046384
4  0.814254  0.450993  0.610867  0.434545  0.854719  0.816421  0.526713

        xx8       xx9      xx10  ...      xx42      xx43      xx44      xx45  \
0  0.112473  0.170478  0.083614  ...  0.751828  0.253542  0.201421  0.000142
1  0.000975  0.553863  0.657753  ...  0.073658  0.018109  0.000001  0.015828
2  0.468239  0.045595  0.252255  ...  0.471873  0.003426  0.872730  0.451597
3  0.124263  0.080838  0.147356  ...  0.339936  0.337921  0.307293  0.174741
4  0.746686  0.110237  0.012989  ...  0.862799  0.100622  0.043526  0.003430

       xx46      xx47      xx48      xx49      xx50        xx
0  0.271941  0.016613  0.040522  0.005240  0.408884  3.454535
1  0.075922  0.054690  0.040076  0.543140  0.075653  4.194989
2  0.460444  0.858384  0.025924  0.005482  0.094649  4.138815
3  0.084996  0.558338  0.261469  0.136989  0.000034  3.646531
4  0.192976  0.382419  0.023165  0.214064  0.014918  4.054355

[5 rows x 51 columns]

In [84]:
def vector_len(data, new_df, vector_len, col_name, variable):
    new_df = pd.DataFrame()
    for i in range(1, vector_len):
        new_df[col_name + str(i)] = 0
        new_df[col_name + str(i)] = data[variable + str(i)] ** 2
    new_df[col_name + '_sum'] = new_df.sum(axis=1) ** .5
    print(new_df.head())
    return new_df

In [85]:
vector_len(cos1, d, cos1_len, 'xx', 'x')

        xx1       xx2       xx3       xx4       xx5       xx6       xx7  \
0  0.578056  0.085515  0.048237  0.300841  0.007878  0.921619  0.017836
1  0.860590  0.878344  0.495884  0.439887  0.136863  0.001092  0.738843
2  0.359664  0.749402  0.970856  0.082714  0.087515  0.059429  0.338782
3  0.181135  0.128982  0.847504  0.028365  0.150816  0.028184  0.046384
4  0.814254  0.450993  0.610867  0.434545  0.854719  0.816421  0.526713

        xx8       xx9      xx10  ...      xx42      xx43      xx44      xx45  \
0  0.112473  0.170478  0.083614  ...  0.751828  0.253542  0.201421  0.000142
1  0.000975  0.553863  0.657753  ...  0.073658  0.018109  0.000001  0.015828
2  0.468239  0.045595  0.252255  ...  0.471873  0.003426  0.872730  0.451597
3  0.124263  0.080838  0.147356  ...  0.339936  0.337921  0.307293  0.174741
4  0.746686  0.110237  0.012989  ...  0.862799  0.100622  0.043526  0.003430

       xx46      xx47      xx48      xx49      xx50    xx_sum
0  0.271941  0.016613  0.040522  0.005240  0.408884  3.454535
1  0.075922  0.054690  0.040076  0.543140  0.075653  4.194989
2  0.460444  0.858384  0.025924  0.005482  0.094649  4.138815
3  0.084996  0.558338  0.261469  0.136989  0.000034  3.646531
4  0.192976  0.382419  0.023165  0.214064  0.014918  4.054355

[5 rows x 51 columns]

,xx1,xx2,xx3,xx4,xx5,xx6,xx7,xx8,xx9,xx10,...,xx42,xx43,xx44,xx45,xx46,xx47,xx48,xx49,xx50,xx_sum
0,0.578056,0.085515,0.048237,0.300841,0.007878,0.921619,0.017836,0.112473,0.170478,0.083614,...,0.751828,0.253542,0.201421,0.000142,0.271941,0.016613,0.040522,0.005240,0.408884,3.454535
1,0.860590,0.878344,0.495884,0.439887,0.136863,0.001092,0.738843,0.000975,0.553863,0.657753,...,0.073658,0.018109,0.000001,0.015828,0.075922,0.054690,0.040076,0.543140,0.075653,4.194989
2,0.359664,0.749402,0.970856,0.082714,0.087515,0.059429,0.338782,0.468239,0.045595,0.252255,...,0.471873,0.003426,0.872730,0.451597,0.460444,0.858384,0.025924,0.005482,0.094649,4.138815
3,0.181135,0.128982,0.847504,0.028365,0.150816,0.028184,0.046384,0.124263,0.080838,0.147356,...,0.339936,0.337921,0.307293,0.174741,0.084996,0.558338,0.261469,0.136989,0.000034,3.646531
4,0.814254,0.450993,0.610867,0.434545,0.854719,0.816421,0.526713,0.746686,0.110237,0.012989,...,0.862799,0.100622,0.043526,0.003430,0.192976,0.382419,0.023165,0.214064,0.014918,4.054355
5,0.004318,0.005091,0.846529,0.217072,0.018474,0.067148,0.417381,0.068095,0.002287,0.770094,...,0.026670,0.781562,0.956464,0.001421,0.832729,0.491093,0.369895,0.230083,0.601338,4.082765
6,0.061425,0.611274,0.425887,0.048691,0.724627,0.001444,0.180617,0.072695,0.059634,0.589225,...,0.171082,0.771270,0.140993,0.859941,0.816891,0.661750,0.012866,0.080696,0.083642,3.941104
7,0.735066,0.179064,0.003003,0.007096,0.109554,0.329717,0.873720,0.000055,0.007295,0.715682,...,0.816258,0.014699,0.001362,0.182927,0.296535,0.059673,0.710700,0.296067,0.101067,4.023385
8,0.169629,0.182124,0.137656,0.169859,0.463611,0.977824,0.016817,0.305312,0.616319,0.568606,...,0.608228,0.002552,0.000464,0.025265,0.000547,0.657445,0.031531,0.010341,0.017427,3.957114
9,0.452781,0.767867,0.087652,0.056406,0.551915,0.516084,0.323954,0.405069,0.023985,0.201987,...,0.048207,0.072431,0.699448,0.000529,0.030307,0.794416,0.359544,0.969851,0.008254,3.563819

In [87]:
vector_len(cos2, f, cos2_len, 'yy', 'x')

        yy1       yy2       yy3       yy4       yy5       yy6       yy7  \
0  0.007245  0.507457  0.942453  0.423645  0.124955  0.000113  0.018480
1  0.001043  0.102573  0.000691  0.695373  0.195647  0.104892  0.016404
2  0.090999  0.646352  0.001421  0.005068  0.262287  0.781633  0.843183
3  0.045122  0.360576  0.163176  0.205363  0.526931  0.913668  0.302863
4  0.665138  0.602890  0.054494  0.003042  0.024448  0.964245  0.830796

        yy8       yy9      yy10  ...      yy42      yy43      yy44      yy45  \
0  0.316980  0.579167  0.457436  ...  0.002577  0.016947  0.600377  0.075038
1  0.318513  0.725393  0.119591  ...  0.791032  0.000035  0.449745  0.003264
2  0.558726  0.054789  0.289918  ...  0.000212  0.099332  0.174014  0.071776
3  0.255753  0.141166  0.359832  ...  0.088477  0.052487  0.202959  0.040897
4  0.463557  0.077390  0.010750  ...  0.032127  0.875665  0.963794  0.837042

       yy46      yy47      yy48      yy49      yy50    yy_sum
0  0.093312  0.047699  0.628421  0.525930  0.312079  4.152558
1  0.229738  0.390525  0.029756  0.439649  0.642931  3.500409
2  0.027367  0.005705  0.000554  0.014314  0.054925  3.566516
3  0.071145  0.019271  0.230967  0.827445  0.354811  4.513646
4  0.693872  0.315889  0.678350  0.140970  0.795111  4.512488

[5 rows x 51 columns]

,yy1,yy2,yy3,yy4,yy5,yy6,yy7,yy8,yy9,yy10,...,yy42,yy43,yy44,yy45,yy46,yy47,yy48,yy49,yy50,yy_sum
0,0.007245,0.507457,0.942453,0.423645,0.124955,0.000113,0.018480,0.316980,0.579167,0.457436,...,0.002577,0.016947,0.600377,0.075038,0.093312,0.047699,0.628421,0.525930,0.312079,4.152558
1,0.001043,0.102573,0.000691,0.695373,0.195647,0.104892,0.016404,0.318513,0.725393,0.119591,...,0.791032,0.000035,0.449745,0.003264,0.229738,0.390525,0.029756,0.439649,0.642931,3.500409
2,0.090999,0.646352,0.001421,0.005068,0.262287,0.781633,0.843183,0.558726,0.054789,0.289918,...,0.000212,0.099332,0.174014,0.071776,0.027367,0.005705,0.000554,0.014314,0.054925,3.566516
3,0.045122,0.360576,0.163176,0.205363,0.526931,0.913668,0.302863,0.255753,0.141166,0.359832,...,0.088477,0.052487,0.202959,0.040897,0.071145,0.019271,0.230967,0.827445,0.354811,4.513646
4,0.665138,0.602890,0.054494,0.003042,0.024448,0.964245,0.830796,0.463557,0.077390,0.010750,...,0.032127,0.875665,0.963794,0.837042,0.693872,0.315889,0.678350,0.140970,0.795111,4.512488

In [86]:
vector_len(cos2, a, cos2_len, 'yy', 'x')

NameError: name 'a' is not defined